/**
 * marketIntelligence — Enterprise Market Intelligence/Competitive Intelligence/
 * External Environment Center 순수 로직 (Phase AI-OPS-24).
 *
 * Enterprise → Market → Competition → Industry → External Signals →
 * Market Intelligence → Executive Market Advisory.
 * AI는 시장/산업/경쟁/수요 분석만 — 자동 경쟁사 생성/시장 분석 확정/전략·KPI·예산 변경 없음.
 *
 * Market 정직성(전부 코드로 강제):
 *  - Market Trend ≠ Future Guarantee. Competition ≠ Threat. Opportunity ≠ Success.
 *  - Signal ≠ Fact(observed 시작). Correlation ≠ Causation. Recommendation ≠ Business Decision.
 *  - Unknown 유지(null→0 금지). 표본 부족 sample_too_small. 데이터 부족 insufficient_data.
 *  - 외부 데이터 부족 market_unavailable. 근거 부족 market_unverified.
 *  - deterministic · pure · null 안전 · NaN/Infinity 방어.
 */
import { isFiniteNumber, clampScore } from './aiMemory';
import { classifyTrend, correlateStrategyPerformance } from './performanceIntelligence';

export { classifyTrend };   // Market Trend 는 0525 4분류 재사용(Trend ≠ Future Guarantee)
export const correlateMarketChain = correlateStrategyPerformance;   // Correlation ≠ Causation(0525 재사용)

/* ── 타입 ─────────────────────────────────────────────────────────────── */
export type MarketRiskLevel = 'low' | 'medium' | 'high' | 'unknown';

export const MARKET_SIGNAL_KINDS = ['economic', 'seasonal', 'regulatory', 'technology', 'consumer', 'industry', 'competitor'] as const;
export const MARKET_RISK_KINDS = ['competition_risk', 'demand_risk', 'seasonal_risk', 'regulatory_risk', 'market_uncertainty'] as const;
export const MARKET_OPPORTUNITY_TYPES = ['opportunity_candidate', 'growth_candidate', 'expansion_candidate'] as const;
export const MARKET_RECOMMENDATION_TYPES = ['observe_market', 'review_competitor', 'validate_opportunity', 'review_customer_trend', 'gather_external_evidence', 'monitor_industry'] as const;

/* ── 1) Category/Demand Trend(카테고리별 4분류) ──────────────────────── */
export function analyzeCategoryTrends(rows: { category: string; points: { value: number | null }[] }[] | null): { trends: { category: string; trend: string | null; dataStatus: string; changePct: number | null }[]; trendIsNotFutureGuarantee: true } {
  const trends = (rows ?? []).slice(0, 10).map((r) => {
    const t = classifyTrend(r.points);
    return { category: r.category, trend: t.trend, dataStatus: t.dataStatus, changePct: t.changePct };
  });
  return { trends, trendIsNotFutureGuarantee: true };
}

/* ── 2) Competitive Coverage(사람 입력 프로필만 — Competition ≠ Threat) ── */
export function assessCompetitorCoverage(competitors: { name: string; dataAvailability: string; evidenceCount: number }[] | null): { profiled: number; externalDataAvailable: number; marketUnavailable: number; unverified: string[]; competitionIsNotThreat: true; autoGenerated: false } {
  const list = competitors ?? [];
  return {
    profiled: list.length,
    externalDataAvailable: list.filter((c) => c.dataAvailability === 'external_data_available').length,
    marketUnavailable: list.filter((c) => c.dataAvailability !== 'external_data_available').length,
    unverified: list.filter((c) => c.evidenceCount === 0).map((c) => c.name).slice(0, 10),
    competitionIsNotThreat: true, autoGenerated: false,
  };
}

/* ── 4) Market Signal 검증(observed 시작 — Signal ≠ Fact) ────────────── */
export function validateMarketSignal(s: { kind?: string; title?: string | null; evidence?: string[]; requestedStatus?: string } | null): { errors: string[]; initialStatus: 'observed'; signalIsNotFact: true } {
  const errors: string[] = [];
  if (!s) return { errors: ['signal 입력 없음'], initialStatus: 'observed', signalIsNotFact: true };
  if (!s.kind || !(MARKET_SIGNAL_KINDS as readonly string[]).includes(s.kind)) errors.push('허용되지 않는 signal_kind');
  if (!s.title?.trim()) errors.push('title 필수');
  if (!s.evidence?.length) errors.push('Evidence 필수(market_unverified)');
  if (s.requestedStatus && s.requestedStatus !== 'observed') errors.push('Signal 은 observed 상태로만 시작(Confirmed 시작 금지)');
  return { errors, initialStatus: 'observed', signalIsNotFact: true };
}

/* ── 3) Industry Intelligence(관찰 신호 기반 — 확정 아님) ────────────── */
export function analyzeIndustry(i: { growthSignals: number; riskSignals: number; opportunitySignals: number; evidence: string[] }): { verdict: 'observation_based' | 'market_unverified' | 'insufficient_data'; observationCounts: { growth: number; risk: number; opportunity: number }; notConfirmedConclusion: true } {
  if (!i.evidence.length) return { verdict: 'market_unverified', observationCounts: { growth: 0, risk: 0, opportunity: 0 }, notConfirmedConclusion: true };
  const total = i.growthSignals + i.riskSignals + i.opportunitySignals;
  return {
    verdict: total > 0 ? 'observation_based' : 'insufficient_data',
    observationCounts: { growth: i.growthSignals, risk: i.riskSignals, opportunity: i.opportunitySignals },
    notConfirmedConclusion: true,
  };
}

/* ── 5) Regional Pattern(내부 실측만 — Country/City 시장 데이터 없음) ── */
export function analyzeRegionalPattern(regions: { name: string; plays: number | null }[] | null): { shares: { name: string; plays: number; sharePct: number }[]; excludedNull: number; verdict: 'internal_pattern' | 'market_unavailable'; countryCityMarketDataUnavailable: true } {
  const valid = (regions ?? []).filter((r): r is { name: string; plays: number } => r.plays != null && isFiniteNumber(r.plays) && r.plays >= 0);
  const excludedNull = (regions ?? []).length - valid.length;
  if (!valid.length) return { shares: [], excludedNull, verdict: 'market_unavailable', countryCityMarketDataUnavailable: true };
  const total = valid.reduce((a, r) => a + r.plays, 0);
  return {
    shares: valid.map((r) => ({ name: r.name, plays: r.plays, sharePct: total > 0 ? Math.round((r.plays / total) * 10000) / 100 : 0 })).sort((a, b) => b.plays - a.plays).slice(0, 12),
    excludedNull, verdict: 'internal_pattern', countryCityMarketDataUnavailable: true,
  };
}

/* ── 6) Customer Behavior(내부 실측 활용) ────────────────────────────── */
export function analyzeCustomerBehavior(i: { hourCounts: Record<string, number> | null; sessionCount: number | null; playlistsPlayed: number | null; playlistsTotal: number | null }): { peakHours: number[]; adoptionPct: number | null; verdict: 'behavior_measured' | 'insufficient_data'; internalDataOnly: true } {
  const hours = Object.entries(i.hourCounts ?? {}).map(([h, n]) => ({ h: Number(h), n })).filter((x) => Number.isInteger(x.h) && x.h >= 0 && x.h <= 23 && isFiniteNumber(x.n));
  const peakHours = hours.sort((a, b) => b.n - a.n).slice(0, 3).map((x) => x.h);
  const adoptionPct = i.playlistsPlayed != null && i.playlistsTotal != null && i.playlistsTotal > 0
    ? clampScore((i.playlistsPlayed / i.playlistsTotal) * 100) : null;
  const verdict = hours.length || i.sessionCount != null ? 'behavior_measured' : 'insufficient_data';
  return { peakHours, adoptionPct, verdict, internalDataOnly: true };
}

/* ── 7) Market Opportunity(후보만 — 확정 아님) ───────────────────────── */
export function proposeMarketOpportunity(i: { type: string; basis: string; evidence: string[]; unknownFactors: string[] }):
  | { rejected: true; rejectReason: string }
  | { type: string; basis: string; evidence: string[]; confidence: number | null; unknownFactors: string[]; opportunityIsNotSuccess: true; notConfirmed: true; humanApprovalRequired: true } {
  if (!(MARKET_OPPORTUNITY_TYPES as readonly string[]).includes(i.type)) return { rejected: true, rejectReason: `허용되지 않는 opportunity type: ${i.type}` };
  if (!i.evidence.length) return { rejected: true, rejectReason: 'Evidence 없는 기회 제안 금지(market_unverified)' };
  if (!i.basis.trim()) return { rejected: true, rejectReason: 'basis 필수' };
  return {
    type: i.type, basis: i.basis, evidence: i.evidence.slice(0, 10),
    confidence: clampScore(Math.max(0, 60 - i.unknownFactors.length * 15)),
    unknownFactors: i.unknownFactors.slice(0, 10),
    opportunityIsNotSuccess: true, notConfirmed: true, humanApprovalRequired: true,
  };
}

/* ── 8) Market Risk(Low/Medium/High/Unknown 만) ──────────────────────── */
export function assessMarketRisk(i: { kind: string; signal: number | null; highThreshold: number; mediumThreshold: number; evidence: string[] }): { kind: string; level: MarketRiskLevel; verdict: 'ok' | 'market_unverified'; notFactualClaim: true } {
  if (!(MARKET_RISK_KINDS as readonly string[]).includes(i.kind)) return { kind: i.kind, level: 'unknown', verdict: 'market_unverified', notFactualClaim: true };
  if (!i.evidence.length) return { kind: i.kind, level: 'unknown', verdict: 'market_unverified', notFactualClaim: true };
  if (i.signal == null || !isFiniteNumber(i.signal)) return { kind: i.kind, level: 'unknown', verdict: 'ok', notFactualClaim: true };
  const level: MarketRiskLevel = i.signal >= i.highThreshold ? 'high' : i.signal >= i.mediumThreshold ? 'medium' : 'low';
  return { kind: i.kind, level, verdict: 'ok', notFactualClaim: true };
}

/* ── 11) Executive Market Briefing(자동 발송 없음) ───────────────────── */
export const MARKET_BRIEFING_PERIODS = ['today', 'weekly', 'monthly', 'quarterly'] as const;

export function buildMarketBriefing(i: { periodKind: string; marketChanges: string[]; opportunities: string[]; risks: string[]; unknownFactors: string[]; recommendations: string[] }): { periodKind: string; valid: boolean; sections: { key: string; items: string[] }[]; autoSendDisabled: true; signalIsNotFact: true } {
  return {
    periodKind: i.periodKind,
    valid: (MARKET_BRIEFING_PERIODS as readonly string[]).includes(i.periodKind),
    sections: [
      { key: 'market_changes', items: i.marketChanges.slice(0, 10) },
      { key: 'opportunities', items: i.opportunities.slice(0, 10) },
      { key: 'risks', items: i.risks.slice(0, 10) },
      { key: 'unknown_factors', items: i.unknownFactors.slice(0, 10) },
      { key: 'recommendations', items: i.recommendations.slice(0, 10) },
    ],
    autoSendDisabled: true, signalIsNotFact: true,
  };
}

/* ── 12) Market Recommendation(6종 whitelist·Evidence 필수) ──────────── */
export function buildMarketRecommendation(i: { type: string; reason: string; evidence: string[]; confidence: number | null; alternatives?: string[]; assumptions: string[] }):
  | { rejected: true; rejectReason: string }
  | { type: string; reason: string; evidence: string[]; confidence: number | null; alternatives: string[]; assumptions: string[]; limitations: string[]; humanApprovalRequired: true; approvalImplied: false } {
  if (!(MARKET_RECOMMENDATION_TYPES as readonly string[]).includes(i.type)) return { rejected: true, rejectReason: `허용되지 않는 recommendation type: ${i.type}` };
  if (!i.evidence.length) return { rejected: true, rejectReason: 'Evidence 없는 권고 금지(market_unverified)' };
  if (!i.reason.trim()) return { rejected: true, rejectReason: 'Reason 필수' };
  return {
    type: i.type, reason: i.reason, evidence: i.evidence.slice(0, 10),
    confidence: i.confidence != null && isFiniteNumber(i.confidence) ? clampScore(i.confidence) : null,
    alternatives: (i.alternatives ?? []).slice(0, 5), assumptions: i.assumptions.slice(0, 10),
    limitations: ['Recommendation ≠ Business Decision', 'Market Trend ≠ Future Guarantee', 'Signal ≠ Fact'],
    humanApprovalRequired: true, approvalImplied: false,
  };
}

/* ── 10) Executive Market Dashboard(7영역) ───────────────────────────── */
export function buildMarketDashboard(i: { categoriesTracked: number; signalsObserved: number; competitorsProfiled: number; competitorsUnavailable: number; opportunitiesProposed: number; risksHigh: number; behaviorVerdict: string; summaryNote: string | null }): { sections: { key: string; headline: string; detail: string }[]; humanDecisionRequired: true; marketConclusionConfirmed: false } {
  const n = (x: number) => (isFiniteNumber(x) ? String(x) : 'insufficient_data');
  return {
    sections: [
      { key: 'market_overview', headline: n(i.categoriesTracked), detail: '내부 카테고리 실측(외부 시장 데이터 없음)' },
      { key: 'industry', headline: n(i.signalsObserved), detail: 'observed signal — Signal ≠ Fact' },
      { key: 'competition', headline: n(i.competitorsProfiled), detail: `사람 입력 프로필 · market_unavailable ${n(i.competitorsUnavailable)} — Competition ≠ Threat` },
      { key: 'opportunities', headline: n(i.opportunitiesProposed), detail: 'Opportunity ≠ Success(확정 아님)' },
      { key: 'risks', headline: n(i.risksHigh), detail: 'high risk 건수 — 사실 단정 아님' },
      { key: 'customer_trend', headline: i.behaviorVerdict, detail: '내부 행동 실측 기반' },
      { key: 'executive_summary', headline: i.summaryNote ? 'note' : 'insufficient_data', detail: i.summaryNote ?? '요약 입력 없음 — unknown 유지' },
    ],
    humanDecisionRequired: true, marketConclusionConfirmed: false,
  };
}

/* ── Support Matrix ──────────────────────────────────────────────────── */
export const MARKET_SUPPORT: { key: string; status: 'supported' | 'partial' | 'unsupported'; note: string }[] = [
  { key: 'category_trend', status: 'supported', note: 'playback store_type_slug 일별 실측' },
  { key: 'customer_demand_trend', status: 'partial', note: '내부 재생 수요만 — 외부 수요 데이터 없음' },
  { key: 'customer_behavior', status: 'supported', note: '시간대/세션/디바이스/Playlist 채택 실측' },
  { key: 'seasonal_trend', status: 'partial', note: '내부 시계열만 — 계절성 시장 데이터셋 없음' },
  { key: 'regional_pattern', status: 'partial', note: 'enterprise_regions 조직 실측 — Country/City 시장 데이터 없음' },
  { key: 'competitor_profile', status: 'supported', note: '사람 입력만(자동 생성 금지) — Competition ≠ Threat' },
  { key: 'competitor_observation', status: 'supported', note: '관찰 이벤트 기록 — 사실 단정 아님' },
  { key: 'market_signal', status: 'supported', note: 'observed 강제 시작 — Signal ≠ Fact' },
  { key: 'industry_intelligence', status: 'partial', note: '관찰 신호 기반만 — 산업 데이터셋 없음' },
  { key: 'market_opportunity', status: 'supported', note: '후보 제안만 — Opportunity ≠ Success' },
  { key: 'market_risk', status: 'supported', note: 'Low/Medium/High/Unknown — Evidence 필수' },
  { key: 'market_correlation', status: 'supported', note: '0525 재사용 — Correlation ≠ Causation' },
  { key: 'market_briefing', status: 'supported', note: 'Today/Weekly/Monthly/Quarterly — 자동 발송 없음' },
  { key: 'external_market_dataset', status: 'unsupported', note: '산업/경제/규제/소비자 조사 원본 없음 — market_unavailable' },
  { key: 'auto_competitor_creation', status: 'unsupported', note: '자동 경쟁사 생성 금지' },
  { key: 'auto_market_conclusion', status: 'unsupported', note: '시장 분석 자동 확정/전략 자동 변경 금지' },
];
