import { describe, expect, it } from 'vitest';
import {
  analyzeCategoryTrends,
  analyzeCustomerBehavior,
  analyzeIndustry,
  analyzeRegionalPattern,
  assessCompetitorCoverage,
  assessMarketRisk,
  buildMarketBriefing,
  buildMarketDashboard,
  buildMarketRecommendation,
  correlateMarketChain,
  MARKET_SUPPORT,
  proposeMarketOpportunity,
  validateMarketSignal,
} from './marketIntelligence';

describe('category trend — 4분류 재사용', () => {
  it('카테고리별 trend + 표본 방어 + Future Guarantee 아님', () => {
    const r = analyzeCategoryTrends([
      { category: 'cafe', points: [{ value: 10 }, { value: 10 }, { value: 20 }, { value: 20 }] },
      { category: 'gym', points: [{ value: 1 }, { value: 2 }] },
    ]);
    expect(r.trends[0].trend).toBe('improving');
    expect(r.trends[1].dataStatus).toBe('sample_too_small');
    expect(r.trendIsNotFutureGuarantee).toBe(true);
  });
});

describe('competitor — 사람 입력만', () => {
  it('coverage: market_unavailable 집계 + Competition ≠ Threat + autoGenerated=false', () => {
    const r = assessCompetitorCoverage([
      { name: 'A', dataAvailability: 'external_data_available', evidenceCount: 2 },
      { name: 'B', dataAvailability: 'market_unavailable', evidenceCount: 0 },
    ]);
    expect(r.profiled).toBe(2);
    expect(r.externalDataAvailable).toBe(1);
    expect(r.marketUnavailable).toBe(1);
    expect(r.unverified).toContain('B');
    expect(r.competitionIsNotThreat).toBe(true);
    expect(r.autoGenerated).toBe(false);
  });
});

describe('signal — observed 시작·Signal ≠ Fact', () => {
  it('kind whitelist + Evidence 필수 + Confirmed 시작 거부', () => {
    expect(validateMarketSignal(null).errors).toContain('signal 입력 없음');
    expect(validateMarketSignal({ kind: 'bogus', title: 't', evidence: ['e'] }).errors).toContain('허용되지 않는 signal_kind');
    expect(validateMarketSignal({ kind: 'seasonal', title: 't', evidence: [] }).errors).toContain('Evidence 필수(market_unverified)');
    const forced = validateMarketSignal({ kind: 'economic', title: 't', evidence: ['e'], requestedStatus: 'confirmed' });
    expect(forced.errors.some((e) => e.includes('observed 상태로만 시작'))).toBe(true);
    const ok = validateMarketSignal({ kind: 'consumer', title: '수요 변화 관찰', evidence: ['내부 재생 추이'] });
    expect(ok.errors).toEqual([]);
    expect(ok.initialStatus).toBe('observed');
    expect(ok.signalIsNotFact).toBe(true);
  });
});

describe('industry / regional / behavior', () => {
  it('industry: Evidence 없으면 market_unverified, 신호 기반 관찰만', () => {
    expect(analyzeIndustry({ growthSignals: 1, riskSignals: 0, opportunitySignals: 0, evidence: [] }).verdict).toBe('market_unverified');
    expect(analyzeIndustry({ growthSignals: 0, riskSignals: 0, opportunitySignals: 0, evidence: ['e'] }).verdict).toBe('insufficient_data');
    const r = analyzeIndustry({ growthSignals: 2, riskSignals: 1, opportunitySignals: 1, evidence: ['signals'] });
    expect(r.verdict).toBe('observation_based');
    expect(r.notConfirmedConclusion).toBe(true);
  });
  it('regional: null 제외 + 자료 없으면 market_unavailable + Country/City 없음 명시', () => {
    expect(analyzeRegionalPattern([]).verdict).toBe('market_unavailable');
    const r = analyzeRegionalPattern([{ name: 'cafe', plays: 60 }, { name: 'gym', plays: 40 }, { name: 'x', plays: null }]);
    expect(r.shares[0].sharePct).toBe(60);
    expect(r.excludedNull).toBe(1);
    expect(r.countryCityMarketDataUnavailable).toBe(true);
  });
  it('behavior: peak hours top3 + adoption + internalDataOnly', () => {
    const r = analyzeCustomerBehavior({ hourCounts: { '9': 10, '14': 30, '20': 50, '3': 1 }, sessionCount: 100, playlistsPlayed: 5, playlistsTotal: 10 });
    expect(r.peakHours).toEqual([20, 14, 9]);
    expect(r.adoptionPct).toBe(50);
    expect(r.verdict).toBe('behavior_measured');
    expect(r.internalDataOnly).toBe(true);
    expect(analyzeCustomerBehavior({ hourCounts: null, sessionCount: null, playlistsPlayed: null, playlistsTotal: null }).verdict).toBe('insufficient_data');
  });
});

describe('opportunity / risk', () => {
  it('opportunity: whitelist + Evidence 필수 + Opportunity ≠ Success', () => {
    expect('rejected' in proposeMarketOpportunity({ type: 'guaranteed_win', basis: 'x', evidence: ['e'], unknownFactors: [] })).toBe(true);
    expect('rejected' in proposeMarketOpportunity({ type: 'growth_candidate', basis: 'x', evidence: [], unknownFactors: [] })).toBe(true);
    const r = proposeMarketOpportunity({ type: 'expansion_candidate', basis: '카테고리 재생 증가 관찰', evidence: ['category trend'], unknownFactors: ['외부 수요'] });
    if ('notConfirmed' in r) {
      expect(r.opportunityIsNotSuccess).toBe(true);
      expect(r.notConfirmed).toBe(true);
      expect(r.confidence).toBe(45);
    }
  });
  it('risk: Low/Medium/High/Unknown 만 + Evidence 없으면 market_unverified', () => {
    expect(assessMarketRisk({ kind: 'demand_risk', signal: 90, highThreshold: 80, mediumThreshold: 50, evidence: [] }).verdict).toBe('market_unverified');
    expect(assessMarketRisk({ kind: 'bogus', signal: 90, highThreshold: 80, mediumThreshold: 50, evidence: ['e'] }).level).toBe('unknown');
    expect(assessMarketRisk({ kind: 'competition_risk', signal: 90, highThreshold: 80, mediumThreshold: 50, evidence: ['e'] }).level).toBe('high');
    expect(assessMarketRisk({ kind: 'seasonal_risk', signal: 60, highThreshold: 80, mediumThreshold: 50, evidence: ['e'] }).level).toBe('medium');
    expect(assessMarketRisk({ kind: 'market_uncertainty', signal: null, highThreshold: 80, mediumThreshold: 50, evidence: ['e'] }).level).toBe('unknown');
  });
});

describe('correlation / briefing / recommendation / dashboard / support', () => {
  it('correlation: 0525 재사용 — 표본<5 sample_too_small + ≠ Causation', () => {
    const r = correlateMarketChain([
      { label: 'Market(category) ↔ KPI(listening)', strategySignal: 25, kpiSignal: 30, sample: 10 },
      { label: 'small', strategySignal: 5, kpiSignal: 5, sample: 2 },
    ]);
    expect(r.pairs[0].verdict).toBe('correlation_candidate');
    expect(r.pairs[1].verdict).toBe('sample_too_small');
    expect(r.correlationIsNotCausation).toBe(true);
  });
  it('briefing: 5섹션 + 자동 발송 없음', () => {
    const r = buildMarketBriefing({ periodKind: 'quarterly', marketChanges: ['m'], opportunities: [], risks: ['r'], unknownFactors: ['u'], recommendations: [] });
    expect(r.valid).toBe(true);
    expect(r.sections).toHaveLength(5);
    expect(r.autoSendDisabled).toBe(true);
    expect(buildMarketBriefing({ periodKind: 'hourly', marketChanges: [], opportunities: [], risks: [], unknownFactors: [], recommendations: [] }).valid).toBe(false);
  });
  it('recommendation: whitelist + Evidence 필수 + ≠ Business Decision', () => {
    expect('rejected' in buildMarketRecommendation({ type: 'change_strategy', reason: 'x', evidence: ['e'], confidence: null, assumptions: [] })).toBe(true);
    expect('rejected' in buildMarketRecommendation({ type: 'observe_market', reason: 'x', evidence: [], confidence: null, assumptions: [] })).toBe(true);
    const r = buildMarketRecommendation({ type: 'review_customer_trend', reason: '카테고리 하락 관찰', evidence: ['trend'], confidence: 35, assumptions: ['a'] });
    if ('humanApprovalRequired' in r) {
      expect(r.humanApprovalRequired).toBe(true);
      expect(r.approvalImplied).toBe(false);
      expect(r.limitations).toContain('Recommendation ≠ Business Decision');
    }
  });
  it('dashboard: 7영역 + marketConclusionConfirmed=false', () => {
    const r = buildMarketDashboard({ categoriesTracked: 5, signalsObserved: 2, competitorsProfiled: 1, competitorsUnavailable: 1, opportunitiesProposed: 1, risksHigh: 0, behaviorVerdict: 'behavior_measured', summaryNote: null });
    expect(r.sections).toHaveLength(7);
    expect(r.humanDecisionRequired).toBe(true);
    expect(r.marketConclusionConfirmed).toBe(false);
    expect(r.sections.find((s) => s.key === 'executive_summary')?.headline).toBe('insufficient_data');
  });
  it('MARKET_SUPPORT: 16항목 + 외부 데이터셋/자동 생성/자동 확정 unsupported', () => {
    expect(MARKET_SUPPORT).toHaveLength(16);
    for (const key of ['external_market_dataset', 'auto_competitor_creation', 'auto_market_conclusion']) {
      expect(MARKET_SUPPORT.find((s) => s.key === key)?.status).toBe('unsupported');
    }
  });
});
