-- 0220 — Hard Block taxonomy 시드 (이미 prod 적용)
-- 10개 매장 카테고리: 카페/와인바/헬스장/식당/편집샵/라운지/호텔/미용실/병원/사무실
-- 각 카테고리별 allow/block 룰 — CLAP 점수 무관 즉시 제외 (block)
--                                  추천 강조 (allow)
-- 운영 중 admin UI 로 추가/수정 가능. 본 시드는 v1 출발점.

delete from public.genre_block_rules;

insert into public.genre_block_rules(business_category, block_kind, genre_pattern, reason) values
-- 카페
('카페', 'block', 'hip-hop',     '카페 분위기에 부적합 (강한 비트)'),
('카페', 'block', 'hip hop',     '카페 분위기에 부적합'),
('카페', 'block', 'hiphop',      '카페 분위기에 부적합'),
('카페', 'block', 'k-hiphop',    '카페 분위기에 부적합'),
('카페', 'block', 'rap',         '카페 분위기에 부적합'),
('카페', 'block', 'trap',        '카페 분위기에 부적합'),
('카페', 'block', 'drill',       '카페 분위기에 부적합'),
('카페', 'block', 'edm',         '댄스 음악은 카페 부적합'),
('카페', 'block', 'hardstyle',   '하드코어 EDM 부적합'),
('카페', 'block', 'dubstep',     '하드코어 EDM 부적합'),
('카페', 'block', 'metal',       '메탈 부적합'),
('카페', 'block', 'k-pop dance', '댄스 곡 부적합 (잔잔 카페 한정)'),
('카페', 'allow', 'jazz',         '카페에 가장 잘 어울림'),
('카페', 'allow', 'lo-fi',        '카페 클래식'),
('카페', 'allow', 'lofi',         '카페 클래식'),
('카페', 'allow', 'bossa nova',   '브런치/오전 카페'),
('카페', 'allow', 'acoustic',     '잔잔한 카페'),
('카페', 'allow', 'indie folk',   '잔잔한 카페'),
('카페', 'allow', 'neo soul',     '오후 카페'),
('카페', 'allow', 'city pop',     '브런치 카페 (조용한 것 한정)'),
('카페', 'allow', 'ambient',      '잔잔한 카페'),
-- 와인바
('와인바', 'block', 'hip-hop', '와인바 부적합'),
('와인바', 'block', 'hip hop', '와인바 부적합'),
('와인바', 'block', 'hiphop',  '와인바 부적합'),
('와인바', 'block', 'k-hiphop','와인바 부적합'),
('와인바', 'block', 'rap',     '와인바 부적합'),
('와인바', 'block', 'trap',    '와인바 부적합'),
('와인바', 'block', 'edm',     '와인바 부적합'),
('와인바', 'block', 'hardstyle','와인바 부적합'),
('와인바', 'block', 'metal',   '와인바 부적합'),
('와인바', 'block', 'k-pop',   'K-Pop 댄스 부적합 (성인 매장)'),
('와인바', 'block', 'rock',    '시끄러운 락 부적합'),
('와인바', 'allow', 'jazz', '와인바 최적'),
('와인바', 'allow', 'lounge', '와인바 최적'),
('와인바', 'allow', 'neo soul','와인바 최적'),
('와인바', 'allow', 'r&b', '저녁 와인바'),
('와인바', 'allow', 'french', '와인바'),
('와인바', 'allow', 'chanson','프렌치 와인바'),
('와인바', 'allow', 'downtempo','심야'),
('와인바', 'allow', 'trip-hop','심야'),
('와인바', 'allow', 'classical','고급'),
-- 헬스장
('헬스장', 'block', 'ambient', '에너지 부족'),
('헬스장', 'block', 'sleep', '에너지 부족'),
('헬스장', 'block', 'meditation', '에너지 부족'),
('헬스장', 'block', 'lo-fi', '에너지 부족'),
('헬스장', 'block', 'lofi', '에너지 부족'),
('헬스장', 'block', 'jazz', '잔잔한 곡 부적합'),
('헬스장', 'block', 'bossa nova', '잔잔'),
('헬스장', 'block', 'classical', '클래식 부적합'),
('헬스장', 'block', 'acoustic', '잔잔'),
('헬스장', 'allow', 'edm', '헬스장 최적'),
('헬스장', 'allow', 'hip-hop', '헬스장 최적'),
('헬스장', 'allow', 'k-hiphop','헬스장 최적'),
('헬스장', 'allow', 'trap', '강한 비트'),
('헬스장', 'allow', 'drum & bass','강한 비트'),
('헬스장', 'allow', 'big room','에너지'),
('헬스장', 'allow', 'dance','댄스'),
('헬스장', 'allow', 'k-pop dance','댄스'),
-- 식당
('식당', 'block', 'edm', '식사 방해'),
('식당', 'block', 'hardstyle','식사 방해'),
('식당', 'block', 'metal','식사 방해'),
('식당', 'block', 'trap','식사 방해'),
('식당', 'block', 'drill','식사 방해'),
('식당', 'allow', 'jazz','식사 클래식'),
('식당', 'allow', 'bossa nova','식사 분위기'),
('식당', 'allow', 'acoustic','잔잔'),
('식당', 'allow', 'lounge','식사 분위기'),
('식당', 'allow', 'classical','고급 식당'),
('식당', 'allow', 'world music','에스닉'),
-- 편집샵
('편집샵', 'block', 'metal','편집샵 톤 부적합'),
('편집샵', 'block', 'hardcore','편집샵 톤 부적합'),
('편집샵', 'block', 'gospel','편집샵 톤 부적합'),
('편집샵', 'block', 'traditional','편집샵 톤 부적합'),
('편집샵', 'block', 'classical','편집샵 톤 부적합'),
('편집샵', 'allow', 'indie pop','편집샵 정석'),
('편집샵', 'allow', 'electronic','감각적 일렉트로닉'),
('편집샵', 'allow', 'city pop','편집샵 정석'),
('편집샵', 'allow', 'k-pop','트렌디 편집샵'),
('편집샵', 'allow', 'neo soul','편집샵 정석'),
-- 라운지
('라운지', 'block', 'hip-hop','라운지 부적합'),
('라운지', 'block', 'edm','라운지 부적합'),
('라운지', 'block', 'k-pop','라운지 부적합'),
('라운지', 'block', 'rock','라운지 부적합'),
('라운지', 'block', 'metal','라운지 부적합'),
('라운지', 'block', 'trap','라운지 부적합'),
('라운지', 'allow', 'lounge','라운지 최적'),
('라운지', 'allow', 'jazz','라운지 최적'),
('라운지', 'allow', 'ambient','심야 라운지'),
('라운지', 'allow', 'downtempo','심야 라운지'),
('라운지', 'allow', 'neo classical','고급'),
-- 호텔
('호텔', 'block', 'hip-hop','호텔 라운지 부적합'),
('호텔', 'block', 'edm','호텔 라운지 부적합'),
('호텔', 'block', 'k-pop','호텔 라운지 부적합'),
('호텔', 'block', 'rock','호텔 라운지 부적합'),
('호텔', 'block', 'metal','호텔 라운지 부적합'),
('호텔', 'block', 'trap','호텔 라운지 부적합'),
('호텔', 'allow', 'jazz','호텔 라운지 최적'),
('호텔', 'allow', 'classical','호텔 라운지 최적'),
('호텔', 'allow', 'lounge','호텔 라운지 최적'),
('호텔', 'allow', 'ambient','호텔 라운지'),
('호텔', 'allow', 'neo classical','고급 호텔'),
-- 미용실
('미용실', 'block', 'metal','미용실 부적합'),
('미용실', 'block', 'hardcore','미용실 부적합'),
('미용실', 'block', 'drill','미용실 부적합'),
('미용실', 'block', 'hardstyle','미용실 부적합'),
('미용실', 'allow', 'pop','미용실 정석'),
('미용실', 'allow', 'k-pop','미용실 정석'),
('미용실', 'allow', 'indie pop','미용실 트렌디'),
('미용실', 'allow', 'city pop','미용실 트렌디'),
('미용실', 'allow', 'r&b','미용실 분위기'),
-- 병원
('병원', 'block', 'hip-hop','병원 부적합'),
('병원', 'block', 'edm','병원 부적합'),
('병원', 'block', 'metal','병원 부적합'),
('병원', 'block', 'k-pop','병원 부적합'),
('병원', 'block', 'rock','병원 부적합'),
('병원', 'block', 'trap','병원 부적합'),
('병원', 'allow', 'classical','병원 안정감'),
('병원', 'allow', 'ambient','병원 안정감'),
('병원', 'allow', 'acoustic','병원 안정감'),
('병원', 'allow', 'jazz','병원 분위기'),
('병원', 'allow', 'neo classical','병원 안정감'),
-- 사무실
('사무실', 'block', 'hip-hop','집중 방해'),
('사무실', 'block', 'edm','집중 방해'),
('사무실', 'block', 'k-pop dance','집중 방해'),
('사무실', 'block', 'rock','집중 방해'),
('사무실', 'block', 'metal','집중 방해'),
('사무실', 'block', 'trap','집중 방해'),
('사무실', 'allow', 'lo-fi','사무실 집중 클래식'),
('사무실', 'allow', 'lofi','사무실 집중 클래식'),
('사무실', 'allow', 'ambient','사무실 집중'),
('사무실', 'allow', 'classical','사무실 집중'),
('사무실', 'allow', 'acoustic','사무실 분위기');
